### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by davelab6** [iaolo/iA-Fonts#1]
Please post the source files and build process

**Comment by iaolo** [comment]
IBM doesn't offer a source file yet. I think at this point OTF is the easiest format as you can import it into your font editor of choice (Robotfont, Glyphs, FontLab…).

**Comment by davelab6** [comment]
Sure, they are working on it, but I assume you opened their binary files in some editor, which then created new source files for this project, which were recompiled into the binaries you have here. It's those I'm requesting you publish

**Comment by iaolo** [comment]
I move between Glyphs, Robofont and Fontographer like a crazy person, using UFO as a vessel. Working with the thousands of .glif files that result out of sharing a UFO on GitHub… I'll delete it if this results in chaos. Hoping for IBM to share their source.

**Comment by davelab6** [comment]
Yes, I have faith that they will :) 

UFO should be fairly stable, you can run it through one of the UFO normalizing tools to ensure it. There are 2 I know of, SIL's

https://silnrsi.github.io/FDBP/en-US/UFO.html

    UFOconvert filename.ufo

and the UFO project's, used inside Adobe Type Team:

https://github.com/unified-font-object/ufoNormalizer

**Comment by Xylobol** [comment]
Going to revive this ancient thread now that IBM has had the sources published for a while now.
