### ISSUE TITLE
Incorrect space with m and w

### ISSUE THREAD

**Issue by damianclancig** [iaolo/iA-Fonts#11]
Hi, I use windows 10, and I see that the letters m and w have a bad space with the next letter, they appear very close, as you can see in the attached image. 

I hope it serves to solve this as it is well made letters for reading.

![image](https://user-images.githubusercontent.com/14252266/33274501-01d37246-d36f-11e7-8c16-ed5a4e7f573d.png)

Thank you.

**Comment by iaolo** [comment]
I added ttfs for Windows. Try those, please.

**Comment by der-swing** [comment]
Same as issue #6 - you might work around it by choosing "Standard Ligatures" in programs like Office to resolve the issue. 
But in other software this will *not work*, i.e. setting this font up in Notepad will not look nice.
