### ISSUE TITLE
Cyrillic support is declared, but not really there

### ISSUE THREAD

**Issue by pepelsbey** [iaolo/iA-Fonts#12]
It’s declared in the font info:

![image](https://user-images.githubusercontent.com/105274/33313510-eaffc4fc-d43b-11e7-8d50-c4d463e80a2b.png)

But there’s no Cyrillic symbols in the repertoire

![image](https://user-images.githubusercontent.com/105274/33313594-2bd5820a-d43c-11e7-8d13-ac5c6a747581.png)

Though I can clearly see Cyrillic support in iA Writer app for macOS

![image](https://user-images.githubusercontent.com/105274/33313902-1b3d5886-d43d-11e7-9dfc-09b649e5171a.png)

Do you use another version of this font for the app?

**Comment by iaolo** [comment]
One of the three editors I use must have sneaked it in. Will fix. In iA Writer's version there is no Cyrillic either. What you have there in your screenshot is Nitti. Nitti has Cyrillic support. Cyrillic for Plex iA Writer Duo may be out before the end of the year.

**Comment by pepelsbey** [comment]
Thank you :)

**Comment by iaolo** [comment]
![bildschirmfoto 2017-11-28 um 11 28 17 am](https://user-images.githubusercontent.com/439116/33314888-496a141e-d42f-11e7-9d97-fb6aeaab846e.png)

I just checked. It is not in the font definition source.
