### ISSUE TITLE
Provide web font versions of iA Writer Duospace

### ISSUE THREAD

**Issue by ehd** [iaolo/iA-Fonts#13]
It would be useful to have official eot/woff/woff2 versions of iA Writer Duospace similar to [Plex’s web version](https://github.com/IBM/type/tree/master/fonts/Mono/web).

Via [this tweet](https://twitter.com/iAWriter/status/935507870417915910).

**Comment by iaolo** [comment]
Done.

**Comment by ehd** [comment]
Thank you!
