### ISSUE TITLE
Webkit seems to have problems with iA Writer Duospace

### ISSUE THREAD

**Issue by beingalink** [iaolo/iA-Fonts#15]
Glyph spacing seems to be calculated incorrectly for the non-monospaced glyphs (w, W, m, M).
See [image1](https://www.dropbox.com/s/07139fa3ztrghqf/Screenshot%202017-11-24%2015.36.04.png?dl=0) and [image2](https://www.dropbox.com/s/sm7xcjtbyu95zhs/Screenshot%202017-11-24%2015.35.40.png?dl=0). Not sure if this is a webkit issue or a font problem. Please close if this is a webkit bug.

**Comment by onebigclownshoe** [comment]
Were you using the .ttf files or the .otf? Can you detail how/where you're implementing the font?

**Comment by beingalink** [comment]
I tried both, no difference. This is in the textual irc app. But I also exported the channel view and opened it in standard safari on macOS 10.13.1 with the same result. Firefox works fine though.

**Comment by iaolo** [comment]
Okay, please try the newly added web fonts.

**Comment by beingalink** [comment]
OK, how do I do this? Do I need to create a css sheet for that? I just tried the also updated otf font and the problem is still there. Shouldn't the system fonts also just work?

**Comment by beingalink** [comment]
In the end it might actual be a webkit bug. It's just the first time that I experience such a problem so I wanted to report it here too just to be sure. I also created a webkit issue at apple.

**Comment by iaolo** [comment]
Haven't looked into it yet, but Webkit might interpret it as a monospaced and just force same width characters because it doesn't foresee this type of font. I have heard that some people have the same issue with Apple Mail, but can't reproduce it here.

**Comment by beingalink** [comment]
I have a minimal example (save as .html file):
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Font display error</title>
    <style type="text/css">
        html, body {font-family: 'iA Writer Duospace'; font-size: 12pt;}
    </style>
  </head>
  <body>
    <p>Test 1: <a href="https://www.apple.com/">https://www.apple.com</a> – This hyphen clashes with the link</p>
    <p>Test 2: <b>mmmilky</b>: The colon clashes with the fat text</p>
  </body>
</html>
```
Make sure the iA Writer Duospace font is installed and open the html file in Safari.
