### ISSUE TITLE
Break webfont into smaller subsets

### ISSUE THREAD

**Issue by LC43** [iaolo/iA-Fonts#17]
Hi, 

love the font, but using the  .woff2 for regular, bold and italic, is around 97kb.

Is there a chance to release the font in different latin sets, like IBM plex has? 
Each of these are around 14-15kb for latin1 

thanks

**Comment by ehd** [comment]
@LC43 I’ve thought about the same. Are you familiar with how IBM Plex’s toolchain creates the subsets and accompanying CSS? If not, we could check that out and use their approach.

**Comment by LC43** [comment]
hi @ehd , unfortunately, i'm not. I just did a bit of research to see what files IBM used and if they were at this repo.

i did take these notes:
src:
src/unicodes.js
src/families.js
src/weights.js

Script:
`/scripts/generate.js` calls `createFontFace()` in `/scripts/tools/index.js` to generate all the variants.

**Comment by iaolo** [comment]
I suggest you fork for this. The exporting routines already added a lot of complexity.
