### ISSUE TITLE
German ß looks kind of odd.

### ISSUE THREAD

**Issue by haranbane** [iaolo/iA-Fonts#21]
Hey,

compared to the other letters in iA the german ß looks a bit awkward/angular/disharmoniously. 
![Duospace](https://user-images.githubusercontent.com/24619933/35299644-27090b68-0086-11e8-97bd-2ad4e55431dc.png) Duospace
![Duospace](https://user-images.githubusercontent.com/24619933/35299645-2728c08e-0086-11e8-9627-204aa4a3cf93.png) Monospace

Is this desired or unintentionally?

**Comment by mrtzwlkr** [comment]
It looks unfamiliar, yes.
But my heart always jumps a bit because I love the look.

**Comment by haranbane** [comment]
Yeah, my heart also jumps a bit when I see i -, just for other reasons I guess 😄 . Doesn't look like a ß at all imho. Recently asked my colleagues about it and none of them was able to identify it as a ß.

**Comment by haranbane** [comment]
Seems fixed on iOS :) Thanks a lot <3

**Comment by Kogakuklutz** [comment]
https://en.wikipedia.org/wiki/ß

**Comment by mrtzwlkr** [comment]
Well yeah,… if you know the history of that character it isn‘t unfamiliar at all. It’s just a different ligature.

But I totally understand if it feels unfamiliar and the purpose of the font and iA Writer is to cater for the needs of the professional writer not the pleasures of a graphic designer or typographer ;)

So +1 for changing it to more common forms.

**Comment by haranbane** [comment]
So this would be "for the pleasures of a graphic designer or typographer"? https://upload.wikimedia.org/wikipedia/commons/8/8a/Lesehilfe_Fraktur.svg
