### ISSUE TITLE
Add please Cyrillic support!

### ISSUE THREAD

**Issue by Troollios** [iaolo/iA-Fonts#22]
iA Writer supports Cyrillic. Add please Cyrillic support!
Thank you!

**Comment by myandrienko** [comment]
Cyrillic glyphs [were added to Plex](https://github.com/IBM/plex/pull/130) recently, it would be great to have them in Duospace as well.

**Comment by AlexFinn** [comment]
yep, we would like to have Cyrillic support :) Add please!

**Comment by iaolo** [comment]
Yeah, it's on our list, but it will take some time.

**Comment by iaolo** [comment]
Done. Italics are still monospace, but Regular and Bold are duo.
