### ISSUE TITLE
Am not able to install the fonts in OSX High Sierra

### ISSUE THREAD

**Issue by kdamianakis** [iaolo/iA-Fonts#25]
Looks like it complaints that serious damage will happen to the computer if I install them and when I tried to override it nothing happened. I also tried copying the fonts to the Fonts OSX directory directly and also double clicking them - Fonts Book does not recognise them at all. I wonder if there is a fix for this or if there is anyone else with the same problem.

**Comment by AlexFinn** [comment]
I have the same problem.

**Comment by mrtzwlkr** [comment]
Another great feature font manager (at least FontExplorer) have: 

> Cear font caches. 

Which actually could solve your problem with Ulysses.

**Comment by AlexFinn** [comment]
@kdamianakis 
`brew cask reinstall font-ia-writer-duospace` 
if you have already the fonts or
`brew cask install font-ia-writer-duospace`
can help

**Comment by kdamianakis** [comment]
Hi ΔΛΞΧ <notifications@github.com <mailto:notifications@github.com>>,

I get 

Error: Cask 'font-ia-writer-duospace' is unavailable: No Cask with this name exists.


Kind Regards
Kon Damianakis

**Comment by AlexFinn** [comment]
oh, sorry
first: `brew tap homebrew/cask-fonts`

**Comment by kdamianakis** [comment]
Hi ΔΛΞΧ

Thanks for this - the combination of the commands seems to have worked correctly!

Kind Regards
Kon Damianakis

**Comment by AlexFinn** [comment]
you're welcome! :)

**Comment by iaolo** [comment]
Okay, fixed some issues that might be related. Please update.
