### ISSUE TITLE
The letter æ

### ISSUE THREAD

**Issue by jkelstrup** [iaolo/iA-Fonts#26]
I really like the idea - and result - of duospace!

One thing I very quickly noticed though, was that the Danish (and Norwegian, etc) letter **æ** looks very crammed compared to all the other very well balanced letters.

[Being a ligature](https://en.wikipedia.org/wiki/%C3%86) of the letters _a_ and _e_, **æ** is naturally a quite wide letter.

My suggestion is therefore, to give **æ** the same 1.5 width as m, M, w and W.

Thanks for the consideration!

**Comment by LoganDark** [comment]
@iaolo

**Comment by iaolo** [comment]
Yeah. This will come in the next batch together with @ and some others.

**Comment by iaolo** [comment]
done
