### ISSUE TITLE
Web fonts / iA Writer Quattro / Bold Italic: capital Umlauts do not work

### ISSUE THREAD

**Issue by ghost** [iaolo/iA-Fonts#37]
On websites, with Windows (Chrome & Firefox), there seems to be an error with capital umlauts on the Bold Italic subset; they're not being loaded. Works fine on MacOS, of course.

Also, when creating an image with PHP, the same applies.

I hope it's just me. If I can provide anything else or be of help, I'll gladly help. Love this font!

**Comment by benwf** [comment]
To migitate this issue in the meantime, I'll have the umlauts forced to be displayed lowercase on Windows, if you wonder where the described error is. Simply putting in any capital Umlaut in any Bold Italic text reveals this issue.

**Comment by quittenkaes** [comment]
I'm having the same issues with the TTF fonts under Win 10. Capital umlauts (ÄÖÜ) don't work with the "iA Writer Duo" and "Quattro" fonts.

"Duospace" and "Mono" are working fine.

**Comment by iaolo** [comment]
Not sure what the reason is. Windows and fonts are a very delicate matter. There's a new version coming. Hopefully, the font export fixes it this time.
