### ISSUE TITLE
iA Quattro S — Italic Becomes Bold Italic on iOS

### ISSUE THREAD

**Issue by firexcy** [iaolo/iA-Fonts#38]
When using iA Quattro Statics on iOS (sideloaded with configuration profile), all italic characters are displayed in bold italic instead.

**Comment by lmischer** [comment]
I had a similar issue, seems to be caused by typo in meta data of ttf:
- bold is named Regular
- bold italic is named Italic

**Comment by iaolo** [comment]
Will be fixed in next update.

**Comment by jenningsb2** [comment]
Thanks @bilal-khan !
