### ISSUE TITLE
Em Dash

### ISSUE THREAD

**Issue by ToddOhl** [iaolo/iA-Fonts#4]
Why not make it as wide as the m?

If a similar difference could be found between the en dash and Hyphen, it would help make the differences in dashes more readily apparent with this type of spacing.

**Comment by iaolo** [comment]
Thanks for point this out. Fixed.

**Comment by ToddOhl** [comment]
Nice!

Are you planning to update the version in iA Writer to add the extra length? 

It looks like it's still the old one in the Mac App, but the extra half-space in your new version does make a difference when used in other editors.

Thanks for this!
