### ISSUE TITLE
Missing Greek Glyphs

### ISSUE THREAD

**Issue by Arty2** [iaolo/iA-Fonts#40]
The following Greek characters seem to be have missing glyphs:
## Duo S
Ώ (capital accented omega)

## Duospace
Δ (capital delta)
Ώ (capital accented omega)

## Quatro S
Ώ (capital accented omega)

**Comment by adamdicarlo** [comment]
µ (micro sign, 00B5 / greek small letter mu 03BC) is also missing.

**Comment by iaolo** [comment]
Duospace is an obsolete set, I kept it for archiving reasons, but it created a lot of confusion and update requests. 

Now, I checked the font files, and Omegatonos is present. In what situation does the character not show?

<img width="1224" alt="Screenshot 2023-03-26 at 18 38 13" src="https://user-images.githubusercontent.com/439116/227790506-7e9b30f5-3690-4830-88b1-78034d51add7.png">

**Comment by adamdicarlo** [comment]
I'm not sure, now. I ran into the issue at my old job, where we were using DuoSpace in our product.

**Comment by iaolo** [comment]
I found it. The glyphs were there but some meta information was different between some of the fonts. Had to rebuild. Now it works. Update is coming soon. I build Modern Greek for Mono and all the Italics. Thanks for pointing me to it. Old Greek will still be in Duo and Quattro only. Doesn't fit into Monospace. There's no technical need for Italics in ancient Greek. Would be nice to have, but I'll skip that for now as well. It's a crazy amount of work for a tiny tiny group that would want that.
