### ISSUE TITLE
Numero symbol (№) is unnecessarily narrow in Duo and Quattro

### ISSUE THREAD

**Issue by arzg** [iaolo/iA-Fonts#42]
The numero symbol № is a standard monospace character in all of the iA fonts, leading it to be (given the constraints) unavoidably squished. However, if more space is allowed for it in the Duo and Quattro fonts (similar to how the @ is handled currently), its proportions would look more natural.

**Comment by iaolo** [comment]
There are plenty of others like that. Will be fixed in next update.

**Comment by arzg** [comment]
It’s awesome to see these fonts still being developed! Thanks for your work over the years on iA Writer, which IMO is a shining example of what software can be :)
