### ISSUE TITLE
Plex curly braces {} are so bad

### ISSUE THREAD

**Issue by mvasilkov** [iaolo/iA-Fonts#43]
Hi, seeing how you've fixed other things inherited from the IBM Plex Mono font, such as the lowercase f being square, could you also consider making sane curly braces please?

I love iA Writer, and I've been configuring my other text editors (Vim, VS Code) after its looks for years, Nitti and all. However, coding in any C-style language with the Lovecraftian Plex squigglies is inconceivable.

Thanks for making great software BTW!

**Comment by iaolo** [comment]
Yeah, they're quite opinionated. I'll keep that in mind, but, right now, I have other fish to fry. :-)

**Comment by iaolo** [comment]
Okay, done. coming in next update. Only regular though, not italic.

**Comment by mvasilkov** [comment]
Thank you so much :)
