### ISSUE TITLE
iA Quattro V and font weights when toggling italics

### ISSUE THREAD

**Issue by inklesspen** [iaolo/iA-Fonts#45]
I've installed iA Quattro V system-wide on my Mac. (I've also installed it into a few apps on my iPad.) If I'm typing with the 'Regular' font weight, then hit Cmd-I for italics, type something, and hit Cmd-I to go back to roman type, it switches into the 'Text' font weight instead of 'Regular'. This is very disconcerting.

**Comment by iaolo** [comment]
Will be fixed in the next update.
