### ISSUE TITLE
Duo is not duospace

### ISSUE THREAD

**Issue by eweracs** [iaolo/iA-Fonts#46]
Hi, as is actually already pretty clearly visible in the blog entry on Duo, the font isn't actually duospace. Example: typing two m should require the same space as three i, according to the specifications. It doesn't. Is this by design, or not on purpose? The former would also be absolutely fine, I just find it is a shame and would be happy to work on the files, as I am a type designer myself. So, in case it is not intentional and Duo should, in fact, be meant to be truly duospace, please let me know! I love the modified Plex and am modifying Duo for my own uses already anyway as a truly duospace font. I'm happy to share them if needed. Cheers!

**Comment by colelawrence** [comment]
@eweracs, which specifications are you referring to?

**Comment by colelawrence** [comment]
Never mind! I found what you were referring to in the blog post https://ia.net/topics/in-search-of-the-perfect-writing-font#what-is-duospace

**Comment by eweracs** [comment]
@colelawrence Hi! I am referring to the iA article written on the matter – https://ia.net/topics/in-search-of-the-perfect-writing-font

Already in the images, it is pretty easy to see that the widths of the characters don't actually match up to fit a duospace grid (just look at the Glyph positioning of the characters within the boxes towards the end of the line). It occurred to me while using it within iA Writer, as the ends of the lines were all over the place. Hence, I was intrigued as to whether this non-adherence to the claimed duospace grid was by design or stemmed from something other.

**Comment by iaolo** [comment]
Duo is a legacy version. I'll likely delete it soon. Duospace is Duospace.
