### ISSUE TITLE
Guide to use Variable fonts

### ISSUE THREAD

**Issue by thien-do** [iaolo/iA-Fonts#47]
Hi :D Thanks a lot for the fonts. I've never feel more right about buying iA Writer after reading your a Chrismas Typographic blog post.

It seems that you guys have spent a lot of time to adjust the variable fonts so it looks best in several font sizes, right? I'm just wondering is it possible to share that?

It's because sometimes I'm on a Linux machine and I must use another editor (which is a lot worse than iA Writer) so I tried to replicate the experience as much as possible. I can get the variable quattro to work, but I don't know how should I set other values like line-height and weight and optical etc. based on the font size. Can you guys share that?

Thank you

**Comment by iaolo** [comment]
No. :-)
