### ISSUE TITLE
Could you give a comparison between Duo and Duospace?

### ISSUE THREAD

**Issue by comiluv** [iaolo/iA-Fonts#52]
Hi. Loving the font, using Mono in my npp, VSCode and VS setup.
I got curious as there are other 'versions' other than Mono, and so I read the [blogpost on Duospace](https://ia.net/topics/in-search-of-the-perfect-writing-font) and [an article on Mono, Duo and Quattro](https://ia.net/writer/blog/a-typographic-christmas)
As I finished reading both posts, it seemed to me that there are no differences in files "Duospace" and "Duo". Is there any difference I missed? If so, could you point them out please?
Thank you.

**Comment by antons** [comment]
They both use 2 character widths, but they’re different. The second blog post describes the differences in detail:

> In the latest iteration, we have eliminated the IBM brand-typical features and made look more like the classic iA Writer font. Using square dots instead of round ones, adjusting the swirls and curves on a, j, f, l, t, y, Q, and lots of non-latin characters, we unified mono, Duo, and Quattro under a common look. This was a lot of work.

**Comment by comiluv** [comment]
Then I'd suppose "Mono, Duo, and Quattro" are the most recent versions with latest features and "Duospace" is something with a bit more legacy IBM Plex Mono features? Thanks for the answer!

**Comment by antons** [comment]
@comiluv Yep.
