### ISSUE TITLE
Cursor and text does not line up correctly with iA Writer Mono S

### ISSUE THREAD

**Issue by comiluv** [iaolo/iA-Fonts#53]
1. Environment
OS: Windows 10 version 21H1(build 19043.1083)
Text editor: Visual Studio Code (version 1.57.1)

2. Description of issue
When the user goes through a certain set of letters in a line using arrow key in the text editor, the cursor highlights at wrong places.

3. What actually happens (screenshot)
![iawritermonos](https://user-images.githubusercontent.com/19642705/124773238-bbcfeb80-df77-11eb-8ebc-1a3de33a06be.gif)

4. What's expected to happen
![consolas](https://user-images.githubusercontent.com/19642705/124773290-c7bbad80-df77-11eb-8783-626990754d29.gif)

5. Other stuffs
This issue does not happen with iA Writer Duo S, iA Writer Quattro S, iA Writer Duospace. Only affects iA Writer Mono S.
Also doesn't happen in other text editors, such as Notepad, Notepad++, or Visual Studio

**Comment by comiluv** [comment]
Also posted on https://github.com/microsoft/vscode/issues/128131

**Comment by iaolo** [comment]
That's VS code bug. They fixed it.
