### ISSUE TITLE
Fonts Won't Load in Mac OS Monterey

### ISSUE THREAD

**Issue by mumblequatch** [iaolo/iA-Fonts#55]
Hi there,

I have downloaded each of the TTF font files, but the Font Book in Mac OS Monterey won't accept them. When I try to force-install them, it advises against it, saying there are serious issues with these fonts. 

Is there something I'm doing wrong? 

Also, is there a way to batch-download the fonts rather than clicking/downloading individually?

Thanks,

Mumblequatch

**Comment by iaolo** [comment]
I don't know.
