### ISSUE TITLE
Cannot correctly install Quattro on Windows 11

### ISSUE THREAD

**Issue by manyweare** [iaolo/iA-Fonts#56]
Neither the Variable nor the Static version can be installed properly in Windows 11. This happens if they are installed via the Win11 font settings or the legacy Control Panel.

**Static**
- Installing TTFs in bulk or individually, installs only Regular and Bold Italic
- Win 11's font settings displays all 4 variations as installed
- Control panel shows only Regular and Bold Italic
- Only Regular and Bold Italic available in Word and Adobe CC applications

**Variable**
- Installing the Variable TTFs results in prompt to replace previous font, e.g. installing Italic TTF after Regular results in prompt to replace Quattro Regular font and vice-versa.
- When accepting the replacement, the previous version gets overwritten, e.g. the Italic version overwrites the Regular and vice-versa.

**Comment by ThomasRettig** [comment]
Strange, I'm on Windows too and it works for me.

**Comment by kenmcd** [comment]
> Neither the Variable nor the Static version can be installed properly in Windows 11. This happens if they are installed via the Win11 font settings or the legacy Control Panel.

Do not attempt to use the Quattro variable fonts on Windows.
The name fields inside them are completely messed-up.
And if you attempted to install them along with the static versions you probably have a corrupted Windows font cache.
So completely un-install all the fonts.
Make sure the files are all gone from the Windows Fonts folder.
Delete any leftovers.
Restart your system.
Then install only the four Quattro static fonts.
Those should work.

**Comment by iaolo** [comment]
Variable fonts are not optimized for Windows. We use static fonts in iAW for Windows, too. Windows 11 and fonts is yet another maze.
