### ISSUE TITLE
`1` and `l` is hard to distinguish

### ISSUE THREAD

**Issue by dantezhu** [iaolo/iA-Fonts#58]
<img width="80" alt="image" src="https://user-images.githubusercontent.com/1105212/170434612-702e23b2-13a2-42f5-81ee-acae051c9dbb.png">
maybe this is better?
<img width="117" alt="image" src="https://user-images.githubusercontent.com/1105212/170434640-fc03e01a-91d8-491c-a040-5d39ef0bf066.png">

**Comment by iaolo** [comment]
Thanks. Will be fixed in next update.
