### ISSUE TITLE
iA Presenter mockup font

### ISSUE THREAD

**Issue by quentint** [iaolo/iA-Fonts#59]
Hey!

I think I read somewhere on one of the iA Twitter accounts that a special font was designed for the app mockups seen here: https://ia.net/topics/how-can-we-make-presentations-better

Unfortunately I can't find any link to that tweet 🙁 

Is that true?
If so, could it be committed to this repo?

Some "mockup" fonts exist, but none is really ideal:
- https://www.powermockup.com/blog/fillr-wireframing-font
- https://github.com/los-gordos/BLOKK
- https://github.com/christiannaths/redacted-font

And adding yours to that list could be handy!
What do you think?

**Comment by iaolo** [comment]
I'll keep that in mind.
