### ISSUE TITLE
doesn't seem to work right on Microsoft Word on Windows

### ISSUE THREAD

**Issue by MillerMicroSystems** [iaolo/iA-Fonts#6]
I downloaded and installed the regular (not bold or italic) font and installed it in Windows 10. Then I pulled in some text to check out the font. It comes out monospaced. See attached screen shot.

![duospace screen capture](https://user-images.githubusercontent.com/14025403/33227395-89a1a04e-d167-11e7-8fa7-5ef2894c84a9.JPG)

**Comment by ggruhl** [comment]
Also having this issue with Microsoft Word 2013 on Windows 10.

**Comment by tomulinek** [comment]
Can't be installed under Windows 10 as the install routine notes error (not a valid font in the file).

**Comment by richsuca** [comment]
Click on the otf file, then click _Raw File_. Then install that. It will work but I see the same rendering issue as reported by MillerMicroSystems. Spacing isn't right.

**Comment by der-swing** [comment]
Having the exact same issue with Office 2016 (Word/Powerpoint). Spacing doesn't seem to recognize the dual-spaced W, M, w, m characters.

**Comment by iaolo** [comment]
Please try the newly added ttf fonts to see if that solves the problem.

**Comment by MillerMicroSystems** [comment]
Perfect! Problem solved for me! These new fonts are so much nicer looking too!
