### ISSUE TITLE
Missing character in Quatro font

### ISSUE THREAD

**Issue by pawelgarbo** [iaolo/iA-Fonts#62]
All polish characters are supported in Quatro, except character `ł`
As a result `ł` appears as Mono (fallback):

<img width="192" alt="Screenshot 2023-01-05 at 10 14 02" src="https://user-images.githubusercontent.com/17257692/210744115-1151af65-bd1a-4206-89ad-e55967b3226c.png">

IBM Plex Sans reference:
<img width="459" alt="Screenshot 2023-01-05 at 10 17 44" src="https://user-images.githubusercontent.com/17257692/210744758-a10d3199-df06-4490-818b-d23e24dface7.png">

**Comment by iaolo** [comment]
Thanks. Will be fixed in next update.

**Comment by ghost** [comment]
Are you planning any updates at all? From what I see in the repository, there have been no changes for 5 years.
