### ISSUE TITLE
Component depth exceeds maxp maxComponentDepth in glyph 16

### ISSUE THREAD

**Issue by charlesroper** [iaolo/iA-Fonts#64]
In Firefox, I am seeing the following warning logged to the console when using Quattro Italic (`iAWriterQuattroS-Italic.woff2`). The italic seems to work ok, though.

```
downloadable font: glyf: Component depth exceeds maxp maxComponentDepth in glyph 16, adjust limit to 5.
(font-family: "IAWriter Quattro" style:italic weight:400 stretch:100 src index:0)
```

![2023-03-03_04](https://user-images.githubusercontent.com/176/222844437-e8bacaba-4389-4654-a992-20f2ff89c63d.png)

**Comment by iaolo** [comment]
Seems to be an indicator of how deep the component connections go. I don't know how to fix this without rebuilding lots of stuff. Let's observe first, if this really matters.
