### ISSUE TITLE
Is iA Serif Regular proprietary?

### ISSUE THREAD

**Issue by azzamsa** [iaolo/iA-Fonts#76]
Hi,

I couldn't find `iA Serif Regular` here, as used in the website/blog post.
Is it proprietary?

Thanks!

**Comment by kenmcd** [comment]
From inside the fonts...

Description
`iA Serif is designed by Oliver Reichenstein, released by iA in 2023.`

License Agreement
`No use of this font is allowed without iA’s consent and/or without the user's compliance with the iA728 EULA. Lawful use of the fonts or the data contained within the font files excludes modifying, reassembling, renaming, storing on publicly available servers, redistributing and selling. Any unlawful use of this typographic software will be prosecuted. `

[Edited by iA]~~Which means the answer to your question is `No`.~~

EDIT: Got that backwards. Was thinking No you cannot use it, but the answer is Yes it is proprietary.

**Comment by antons** [comment]
The font is proprietary and is exclusive to iA.

**Comment by azzamsa** [comment]
> The font is proprietary and is exclusive to iA.

Thank you so much for taking time to reply!
