### ISSUE TITLE
I have not install in macOS High Sierra

### ISSUE THREAD

**Issue by sanzcarlos** [iaolo/iA-Fonts#8]
Hello:

I am trying install this fonts in a macos, but the OS A serious error has been detected. Do not use this fonts. Can you help me, please?

Regards,
Carlos Sanz

**Comment by xxdesmus** [comment]
they install fine on High Sierra without issue, perhaps these steps will be helpful for you: https://www.fontspring.com/support/installing/how-do-i-install-fonts-on-my-mac

**Comment by mccombsp-kingco** [comment]
I had the same problem as @sanzcarlos with macos Sierra also when I tried to download from the initial page linked from iA's blog. However, when I clicked each of the four links to the .otf files then on each of the four pages clicked on the "View Raw" link at the bottom of the page in Chrome it downloaded a usable file to my computer.

**Comment by iaolo** [comment]
You can download the whole repo here:

![bildschirmfoto 2017-11-28 um 11 37 57 am](https://user-images.githubusercontent.com/439116/33315352-c1aef240-d430-11e7-89b0-f031ca940c55.png)
