### ISSUE TITLE
Submit a font cask to Homebrew

### ISSUE THREAD

**Issue by infotexture** [iaolo/iA-Fonts#9]
To facilitate updates as **Duospace** evolves along with the upstream **IBM Plex** font family, please consider submitting a font cask to the [homebrew-fonts](https://github.com/caskroom/homebrew-fonts) repository, which makes it easy to install fonts along with other utilities and applications via the [Homebrew](https://brew.sh) package manager and [Homebrew-Cask](https://caskroom.github.io).

For more information, see the corresponding issues and pull requests for IBM Plex:

* https://github.com/IBM/type/issues/70
* https://github.com/caskroom/homebrew-fonts/pull/1365

**Comment by infotexture** [comment]
Looks like this has already been implemented with https://github.com/Homebrew/homebrew-cask-fonts/pull/1381.

(See https://github.com/iaolo/iA-Fonts/issues/25 for caveats.)

**Comment by iaolo** [comment]
This is not my area of expertise, but it looks like this has been solved then.
